// Additional technologies from Devicon and TechIcons
export const extendedTechnologies = [
  // Additional Languages from Devicon
  { name: 'aarch64', category: 'languages' },
  { name: 'apl', category: 'languages' },
  { name: 'ballerina', category: 'languages' },
  { name: 'crystal', category: 'languages' },
  { name: 'deno', category: 'languages' },
  { name: 'elm', category: 'languages' },
  { name: 'fortran', category: 'languages' },
  { name: 'haxe', category: 'languages' },
  { name: 'julia', category: 'languages' },
  { name: 'nim', category: 'languages' },
  { name: 'ocaml', category: 'languages' },
  { name: 'racket', category: 'languages' },
  { name: 'zig', category: 'languages' },

  // Additional Frontend from Devicon/TechIcons
  { name: 'adonisjs', category: 'frontend' },
  { name: 'alpinejs', category: 'frontend' },
  { name: 'antdesign', category: 'frontend' },
  { name: 'astro', category: 'frontend' },
  { name: 'backbonejs', category: 'frontend' },
  { name: 'bulma', category: 'frontend' },
  { name: 'chakraui', category: 'frontend' },
  { name: 'ember', category: 'frontend' },
  { name: 'gatsby', category: 'frontend' },
  { name: 'materialize', category: 'frontend' },
  { name: 'quasar', category: 'frontend' },
  { name: 'svelte', category: 'frontend' },
  { name: 'tauri', category: 'frontend' },
  { name: 'threejs', category: 'frontend' },
  { name: 'vite', category: 'frontend' },
  { name: 'webpack', category: 'frontend' },

  // Additional Backend from Devicon/TechIcons
  { name: 'akka', category: 'backend' },
  { name: 'apachekafka', category: 'backend' },
  { name: 'apachespark', category: 'backend' },
  { name: 'cakephp', category: 'backend' },
  { name: 'codeigniter', category: 'backend' },
  { name: 'drupal', category: 'backend' },
  { name: 'fastapi', category: 'backend' },
  { name: 'fastify', category: 'backend' },
  { name: 'feathersjs', category: 'backend' },
  { name: 'flask', category: 'backend' },
  { name: 'grails', category: 'backend' },
  { name: 'hibernate', category: 'backend' },
  { name: 'krakenjs', category: 'backend' },
  { name: 'ktor', category: 'backend' },
  { name: 'lumen', category: 'backend' },
  { name: 'moleculer', category: 'backend' },
  { name: 'nestjs', category: 'backend' },
  { name: 'phalcon', category: 'backend' },
  { name: 'playwright', category: 'backend' },
  { name: 'quarkus', category: 'backend' },
  { name: 'rails', category: 'backend' },
  { name: 'spring', category: 'backend' },
  { name: 'tomcat', category: 'backend' },
  { name: 'uwsgi', category: 'backend' },

  // Additional Database from Devicon/TechIcons
  { name: 'cockroachdb', category: 'database' },

  // Additional DevOps from Devicon/TechIcons
  { name: 'argocd', category: 'devops' },

  // Additional Tools from Devicon/TechIcons
  { name: 'aftereffects', category: 'tools' },
  { name: 'atom', category: 'tools' },
  { name: 'blender', category: 'tools' },
  { name: 'canva', category: 'tools' },
  { name: 'clion', category: 'tools' },
  { name: 'datagrip', category: 'tools' },
  { name: 'dataspell', category: 'tools' },
  { name: 'dbeaver', category: 'tools' },
  { name: 'eclipse', category: 'tools' },
  { name: 'figma', category: 'tools' },
  { name: 'filezilla', category: 'tools' },
  { name: 'gimp', category: 'tools' },
  { name: 'godot', category: 'tools' },
  { name: 'goland', category: 'tools' },
  { name: 'idea', category: 'tools' },
  { name: 'illustrator', category: 'tools' },
  { name: 'inkscape', category: 'tools' },
  { name: 'insomnia', category: 'tools' },
  { name: 'intellij', category: 'tools' },
  { name: 'jira', category: 'tools' },
  { name: 'lightroom', category: 'tools' },
  { name: 'maya', category: 'tools' },
  { name: 'photoshop', category: 'tools' },
  { name: 'premierepro', category: 'tools' },
  { name: 'processing', category: 'tools' },
  { name: 'pycharm', category: 'tools' },
  { name: 'qodana', category: 'tools' },
  { name: 'rider', category: 'tools' },
  { name: 'sketch', category: 'tools' },
  { name: 'sourcetree', category: 'tools' },
  { name: 'unity', category: 'tools' },
  { name: 'unrealengine', category: 'tools' },
  { name: 'webstorm', category: 'tools' },
  { name: 'xd', category: 'tools' },

  // Additional Testing from Devicon/TechIcons
  { name: 'chai', category: 'testing' },
  { name: 'jasmine', category: 'testing' },
  { name: 'karma', category: 'testing' },
  { name: 'mocha', category: 'testing' },
  { name: 'protractor', category: 'testing' },
  { name: 'rspec', category: 'testing' },
  { name: 'testinglibrary', category: 'testing' },

  // Additional APIs from Devicon/TechIcons
  { name: 'openapi', category: 'apis' },

  // Additional CMS from Devicon/TechIcons
  { name: 'contentful', category: 'cms' },
  { name: 'sanity', category: 'cms' },
  { name: 'strapi', category: 'cms' },
  { name: 'wordpress', category: 'cms' },
];
