export const techCategories = [
  { id: 'languages', name: 'Programming Languages' },
  { id: 'frontend', name: 'Frontend Development' },
  { id: 'backend', name: 'Backend Development' },
  { id: 'mobile', name: 'Mobile Development' },
  { id: 'database', name: 'Databases & Caching' },
  { id: 'devops', name: 'DevOps & Cloud' },
  { id: 'cicd', name: 'CI/CD' },
  { id: 'testing', name: 'Testing' },
  { id: 'monitoring', name: 'Monitoring & Observability' },
  { id: 'dataviz', name: 'Data Visualization' },
  { id: 'apis', name: 'APIs & Communication' },
  { id: 'cms', name: 'CMS' },
  { id: 'tools', name: 'Software & Tools' },
];

export const technologies = [
  // Languages
  { name: 'javascript', category: 'languages' },
  { name: 'typescript', category: 'languages' },
  { name: 'python', category: 'languages' },
  { name: 'java', category: 'languages' },
  { name: 'csharp', category: 'languages' },
  { name: 'go', category: 'languages' },
  { name: 'rust', category: 'languages' },
  { name: 'ruby', category: 'languages' },
  { name: 'php', category: 'languages' },
  { name: 'c', category: 'languages' },
  { name: 'cpp', category: 'languages' },
  { name: 'swift', category: 'languages' },
  { name: 'kotlin', category: 'languages' },
  { name: 'dart', category: 'languages' },
  { name: 'scala', category: 'languages' },
  { name: 'haskell', category: 'languages' },
  { name: 'elixir', category: 'languages' },
  { name: 'clojure', category: 'languages' },
  { name: 'lua', category: 'languages' },
  { name: 'perl', category: 'languages' },
  { name: 'r', category: 'languages' },
  { name: 'bash', category: 'languages' },
  { name: 'powershell', category: 'languages' },
  { name: 'groovy', category: 'languages' },
  { name: 'erlang', category: 'languages' },
  { name: 'ocaml', category: 'languages' },

  // Frontend
  { name: 'html', category: 'frontend' },
  { name: 'css', category: 'frontend' },
  { name: 'sass', category: 'frontend' },
  { name: 'react', category: 'frontend' },
  { name: 'angular', category: 'frontend' },
  { name: 'vue', category: 'frontend' },
  { name: 'svelte', category: 'frontend' },
  { name: 'nextjs', category: 'frontend' },
  { name: 'nuxtjs', category: 'frontend' },
  { name: 'gatsby', category: 'frontend' },
  { name: 'remix', category: 'frontend' },
  { name: 'astro', category: 'frontend' },
  { name: 'tailwindcss', category: 'frontend' },
  { name: 'bootstrap', category: 'frontend' },
  { name: 'materialui', category: 'frontend' },
  { name: 'redux', category: 'frontend' },
  { name: 'webpack', category: 'frontend' },
  { name: 'vite', category: 'frontend' },
  { name: 'threejs', category: 'frontend' },
  { name: 'jquery', category: 'frontend' },
  { name: 'ember', category: 'frontend' },
  { name: 'alpinejs', category: 'frontend' },
  { name: 'blazor', category: 'frontend' },

  // Backend
  { name: 'nodejs', category: 'backend' },
  { name: 'express', category: 'backend' },
  { name: 'nestjs', category: 'backend' },
  { name: 'django', category: 'backend' },
  { name: 'flask', category: 'backend' },
  { name: 'fastapi', category: 'backend' },
  { name: 'rails', category: 'backend' },
  { name: 'spring', category: 'backend' },
  { name: 'laravel', category: 'backend' },
  { name: 'phoenix', category: 'backend' },
  { name: 'nginx', category: 'backend' },
  { name: 'apache', category: 'backend' },
  { name: 'kafka', category: 'backend' },
  { name: 'rabbitmq', category: 'backend' },
  { name: 'celery', category: 'backend' },
  { name: 'symfony', category: 'backend' },

  // APIs & Communication
  { name: 'graphql', category: 'apis' },
  { name: 'apollo', category: 'apis' },
  { name: 'grpc', category: 'apis' },
  { name: 'webrtc', category: 'apis' },
  { name: 'postman', category: 'apis' },

  // Mobile
  { name: 'reactnative', category: 'mobile' },
  { name: 'flutter', category: 'mobile' },
  { name: 'androidstudio', category: 'mobile' },
  { name: 'xcode', category: 'mobile' },
  { name: 'ionic', category: 'mobile' },
  { name: 'xamarin', category: 'mobile' },

  // Database
  { name: 'mongodb', category: 'database' },
  { name: 'mysql', category: 'database' },
  { name: 'postgresql', category: 'database' },
  { name: 'sqlite', category: 'database' },
  { name: 'redis', category: 'database' },
  { name: 'cassandra', category: 'database' },
  { name: 'couchdb', category: 'database' },
  { name: 'dynamodb', category: 'database' },
  { name: 'firebase', category: 'database' },
  { name: 'supabase', category: 'database' },
  { name: 'prisma', category: 'database' },
  { name: 'mariadb', category: 'database' },
  { name: 'cockroachdb', category: 'database' },
  { name: 'influxdb', category: 'database' },
  { name: 'neo4j', category: 'database' },

  // DevOps & Cloud
  { name: 'docker', category: 'devops' },
  { name: 'kubernetes', category: 'devops' },
  { name: 'openshift', category: 'devops' },
  { name: 'aws', category: 'devops' },
  { name: 'azure', category: 'devops' },
  { name: 'gcp', category: 'devops' },
  { name: 'heroku', category: 'devops' },
  { name: 'vercel', category: 'devops' },
  { name: 'netlify', category: 'devops' },
  { name: 'digitalocean', category: 'devops' },
  { name: 'terraform', category: 'devops' },
  { name: 'ansible', category: 'devops' },
  { name: 'linux', category: 'devops' },
  { name: 'ubuntu', category: 'devops' },
  { name: 'arch', category: 'devops' },
  { name: 'vagrant', category: 'devops' },
  { name: 'packer', category: 'devops' },
  { name: 'pulumi', category: 'devops' },

  // CI/CD
  { name: 'jenkins', category: 'cicd' },
  { name: 'githubactions', category: 'cicd' },
  { name: 'gitlab', category: 'cicd' },
  { name: 'circleci', category: 'cicd' },
  { name: 'travisci', category: 'cicd' },
  { name: 'argocd', category: 'cicd' },

  // Monitoring & Observability
  { name: 'prometheus', category: 'monitoring' },
  { name: 'grafana', category: 'monitoring' },
  { name: 'datadog', category: 'monitoring' },
  { name: 'newrelic', category: 'monitoring' },
  { name: 'splunk', category: 'monitoring' },
  { name: 'elastic', category: 'monitoring' },
  { name: 'logstash', category: 'monitoring' },
  { name: 'kibana', category: 'monitoring' },

  // Data Visualization
  { name: 'd3', category: 'dataviz' },
  { name: 'tableau', category: 'dataviz' },
  { name: 'powerbi', category: 'dataviz' },

  // Testing
  { name: 'jest', category: 'testing' },
  { name: 'mocha', category: 'testing' },
  { name: 'chai', category: 'testing' },
  { name: 'cypress', category: 'testing' },
  { name: 'selenium', category: 'testing' },
  { name: 'puppeteer', category: 'testing' },
  { name: 'storybook', category: 'testing' },
  { name: 'testinglibrary', category: 'testing' },
  { name: 'junit', category: 'testing' },

  // Tools
  { name: 'git', category: 'tools' },
  { name: 'github', category: 'tools' },
  { name: 'vscode', category: 'tools' },
  { name: 'vim', category: 'tools' },
  { name: 'neovim', category: 'tools' },
  { name: 'webstorm', category: 'tools' },
  { name: 'idea', category: 'tools' },
  { name: 'figma', category: 'tools' },
  { name: 'xd', category: 'tools' },
  { name: 'ps', category: 'tools' },
  { name: 'ai', category: 'tools' },
  { name: 'yarn', category: 'tools' },
  { name: 'npm', category: 'tools' },
  { name: 'pnpm', category: 'tools' },
  { name: 'maven', category: 'tools' },
  { name: 'gradle', category: 'tools' },
  
  // CMS
  { name: 'wordpress', category: 'cms' },
  { name: 'strapi', category: 'cms' },
  { name: 'contentful', category: 'cms' },
  { name: 'sanity', category: 'cms' },
];
